version: "3.6"
services:
  reddit-scraper:
    build:
      context: ./reddit-scraper
    ports:
      - "8080:8080"
    restart: always
    network_mode: host
    environment:
      REDDIT_CLIENT_ID:
      REDDIT_CLIENT_SECRET:
      REDDIT_USER_AGENT:
  review-service:
    build:
      context: ./review-service
    restart: always
    network_mode: host
    ports:
      - "8180:8180"
  website:
    build:
      context: ./website
    restart: always
    network_mode: host
    environment:
      PORT: "8280"
    ports:
      - "8280:8280"
  sentinel:
    build:
      context: ./sentinel
    restart: always
    network_mode: host
    ports:
      - "8000:8000"
